import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { uploadMedia } from '../lib/storage';
import { LucideX, LucideCamera, LucideLoader2, LucideSave, LucidePackage } from 'lucide-react';

const CATEGORY_PREFIXES = {
    cemento: 'CEM',
    acero: 'ACE',
    aridos: 'ARI',
    pintura: 'PIN',
    herramientas: 'HER',
    equipos: 'EQP',
    general: 'GEN'
};

const MaterialForm = ({ onClose, onSuccess }) => {
    const [loading, setLoading] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [suggestingSKU, setSuggestingSKU] = useState(false);
    const [imagePreview, setImagePreview] = useState(null);
    const [unidades, setUnidades] = useState([]);
    const [formData, setFormData] = useState({
        nombre_interno: '',
        sku: '',
        categoria: 'general',
        descripcion: '',
        unidad_base: '',
        imagen_path: ''
    });

    // Cargar unidades dinámicas desde la DB
    useEffect(() => {
        const fetchUnidades = async () => {
            const { data } = await supabase
                .from('unidades_medida')
                .select('*')
                .order('nombre');
            
            if (data) {
                setUnidades(data);
                // Establecer la primera unidad como predeterminada si no hay una seleccionada
                if (data.length > 0 && !formData.unidad_base) {
                    setFormData(prev => ({ ...prev, unidad_base: data[0].simbolo }));
                }
            }
        };
        fetchUnidades();
    }, []);

    // Sugerir SKU automáticamente al cambiar de categoría
    useEffect(() => {
        const suggestSKU = async () => {
            const prefix = CATEGORY_PREFIXES[formData.categoria] || 'GEN';
            const currentPrefix = formData.sku.split('-')[0];
            const isAutoGenerated = Object.values(CATEGORY_PREFIXES).includes(currentPrefix) || formData.sku === '';

            if (isAutoGenerated) {
                try {
                    setSuggestingSKU(true);
                    const { data, error } = await supabase
                        .from('recursos')
                        .select('sku')
                        .ilike('sku', `${prefix}-%`)
                        .order('sku', { ascending: false })
                        .limit(1);

                    if (error) throw error;

                    let nextNumber = 1;
                    if (data && data.length > 0) {
                        const lastSku = data[0].sku;
                        const lastNumber = parseInt(lastSku.split('-')[1]);
                        if (!isNaN(lastNumber)) {
                            nextNumber = lastNumber + 1;
                        }
                    }

                    const newSku = `${prefix}-${String(nextNumber).padStart(3, '0')}`;
                    setFormData(prev => ({ ...prev, sku: newSku }));
                } catch (err) {
                    console.error('Error sugiriendo SKU:', err);
                } finally {
                    setSuggestingSKU(false);
                }
            }
        };

        suggestSKU();
    }, [formData.categoria]);

    const handleFileChange = async (e) => {
        const file = e.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onloadend = () => setImagePreview(reader.result);
        reader.readAsDataURL(file);

        try {
            setUploading(true);
            const path = await uploadMedia(file, 'materials');
            setFormData({ ...formData, imagen_path: path });
        } catch (error) {
            alert('Error subiendo imagen: ' + error.message);
        } finally {
            setUploading(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            setLoading(true);
            const { error } = await supabase
                .from('recursos')
                .insert([formData]);

            if (error) throw error;
            onSuccess();
            onClose();
        } catch (error) {
            alert('Error al guardar material: ' + error.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex flex-col h-full bg-white dark:bg-slate-900 shadow-2xl animate-in slide-in-from-right duration-300">
            <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-primary/10 text-primary rounded-xl">
                        <LucidePackage size={20} />
                    </div>
                    <h2 className="text-lg font-black text-slate-900 dark:text-white uppercase tracking-tight">Nuevo Material</h2>
                </div>
                <button onClick={onClose} className="p-2 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-full transition-colors">
                    <LucideX size={20} className="text-slate-400" />
                </button>
            </div>

            <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-8 space-y-8">
                <div className="flex justify-center">
                    <div className="relative group w-32 h-32">
                        <div className="w-full h-full rounded-3xl bg-slate-100 dark:bg-slate-800 overflow-hidden border-2 border-dashed border-slate-200 dark:border-slate-700 flex items-center justify-center">
                            {imagePreview ? (
                                <img src={imagePreview} className="w-full h-full object-cover" alt="Preview" />
                            ) : (
                                <LucidePackage size={40} className="text-slate-300" />
                            )}
                        </div>
                        <label className="absolute inset-0 flex items-center justify-center bg-black/40 text-white opacity-0 group-hover:opacity-100 rounded-3xl cursor-pointer transition-opacity">
                            {uploading ? <LucideLoader2 className="animate-spin" /> : <LucideCamera size={24} />}
                            <input type="file" className="hidden" onChange={handleFileChange} accept="image/*" />
                        </label>
                    </div>
                </div>

                <div className="space-y-6">
                    <div>
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block ml-1">Nombre Comercial / Interno</label>
                        <input required value={formData.nombre_interno} onChange={(e) => setFormData({...formData, nombre_interno: e.target.value})} placeholder="Ej: Hidrófugo Líquido" className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-3 text-sm font-bold shadow-sm focus:ring-2 ring-primary/20 outline-none" />
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div className="relative">
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block ml-1">SKU / Código</label>
                            <input value={formData.sku} onChange={(e) => setFormData({...formData, sku: e.target.value.toUpperCase()})} placeholder="HID-001" className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-3 text-sm font-bold shadow-sm focus:ring-2 ring-primary/20 outline-none" />
                            {suggestingSKU && <div className="absolute right-3 bottom-3"><LucideLoader2 size={14} className="animate-spin text-primary" /></div>}
                        </div>
                        <div>
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block ml-1">Categoría</label>
                            <select value={formData.categoria} onChange={(e) => setFormData({...formData, categoria: e.target.value})} className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-3 text-sm font-bold shadow-sm focus:ring-2 ring-primary/20 outline-none appearance-none cursor-pointer">
                                <option value="general">General</option>
                                <option value="cemento">Cementos</option>
                                <option value="acero">Aceros</option>
                                <option value="aridos">Áridos</option>
                                <option value="pintura">Pinturas</option>
                                <option value="herramientas">Herramientas</option>
                                <option value="equipos">Equipos / Maquinaria</option>
                            </select>
                        </div>
                    </div>

                    <div>
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block ml-1">Descripción Técnica</label>
                        <textarea rows={3} value={formData.descripcion} onChange={(e) => setFormData({...formData, descripcion: e.target.value})} placeholder="Especificaciones, marca, etc..." className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-3 text-sm font-bold shadow-sm focus:ring-2 ring-primary/20 outline-none resize-none" />
                    </div>

                    <div className="grid grid-cols-1 gap-4">
                        <div>
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2 block ml-1">Unidad de Gestión</label>
                            <select 
                                value={formData.unidad_base} 
                                onChange={(e) => setFormData({...formData, unidad_base: e.target.value})} 
                                className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-5 py-3 text-sm font-bold shadow-sm focus:ring-2 ring-primary/20 outline-none cursor-pointer"
                            >
                                {unidades.length > 0 ? (
                                    unidades.map(u => (
                                        <option key={u.id} value={u.simbolo}>{u.nombre} ({u.simbolo})</option>
                                    ))
                                ) : (
                                    <option value="">Cargando unidades...</option>
                                )}
                            </select>
                        </div>
                    </div>
                </div>
            </form>

            <div className="p-8 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50">
                <button 
                    disabled={loading || uploading || suggestingSKU} 
                    onClick={handleSubmit}
                    className="w-full py-4 bg-primary text-white rounded-2xl font-black text-[10px] uppercase tracking-widest shadow-xl shadow-primary/20 hover:bg-primary/90 hover:-translate-y-0.5 active:scale-95 transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                >
                    {loading ? <LucideLoader2 className="animate-spin" size={18} /> : <LucideSave size={18} />}
                    Registrar en Inventario
                </button>
            </div>
        </div>
    );
};

export default MaterialForm;
